### ISSUE TITLE
Parsers should be named after the client

### ISSUE THREAD

**Issue by sschuberth** [librariesio/bibliothecary#100]
Right now e.g. the [Maven parser](https://github.com/librariesio/bibliothecary/blob/master/lib/bibliothecary/parsers/maven.rb) also parses Ivy and Gradle files. I believe this is confusing as from a look at the parsers directory it looks as if Ivy and Gradle were not supported.

While it's true that both Ivy and Gradle can also handle Maven repositories, then cam also handle repositories with different layouts. Also, the server-side directory structure is not parsed, but the client-side files, and as such the parses should be named after the client. At the example of the Maven parser, the Ivy and Gradle parses should be split out to separate files.

**Comment by andrew** [comment]
@sschuberth at the moment Libraries.io needs to know the registry that the packages come from, which in Gradles case is still Maven, going to close this for now
