### ISSUE TITLE
Ignore /vendor directory

### ISSUE THREAD

**Issue by andrew** [librariesio/bibliothecary#371]
`vendor` seems to be a dumping ground for third party code, including their dependency manifests, we should add it as an ignored path.

Config for ignored paths is here: https://github.com/librariesio/bibliothecary/blob/master/lib/bibliothecary.rb#L35

Tests are here: https://github.com/librariesio/bibliothecary/blob/master/spec/bibliothecary_spec.rb#L60

**Comment by m1guelpf** [comment]
@andrew Can I take this?

**Comment by andrew** [comment]
@m1guelpf absolutely!
