### ISSUE TITLE
Huge email dump in this repository

### ISSUE THREAD

**Issue by eonist** [librariesio/bibliothecary#403]
Heads up.

I don't know how it happened, probably an accident. 

Are you aware or?

**Comment by andrew** [comment]
Not sure what you mean

**Comment by eonist** [comment]
In this repository there is a huge file dump of emails. Perfect for spam list etc. I can email you the exact location as I don’t want to highlight where it is.

**Comment by andrew** [comment]
Can you email me? andrew@libraries.io

**Comment by eonist** [comment]
sent you an email now

**Comment by andrew** [comment]
I have removed the offending files from the repo that they were in, thanks for reporting
