### ISSUE TITLE
Parsing require*.txt for Pypi dependencies

### ISSUE THREAD

**Issue by jdossett** [librariesio/bibliothecary#404]
There appears to be a bug in the parser for Pypi dependency parsing that causes many files that dont have dependency information in them to be picked up.  In the Readme, the following file formats are listed as being supported:

* req*.txt
* req*.pip
* requirements/*.txt
* requirements/*.pip

If my understanding is correct this means that only files immediately contained in the requirements/ folder should be parsed, and not text files further down unless they match one of the other patterns.  

The regex used in bibliothecary/lib/bibliothecary/parsers/pypi.rb though catches all files that start with
"require" and end with ".txt" or ".pip", regardless of their depth within the tree. 

~~~python
    {
            /^(?!node_modules).*require.*\.(txt|pip)$/ => {
            kind: 'manifest',
            parser: :parse_requirements_txt
    },
~~~

A file like "require/some/other/folder/myhomework.txt" would be considered a file containing dependency information with the coded regex pattern.

This means a lot of fake dependencies get caught by the parser.  Perhaps the regex should be changed in order to better catch the files that are desired.

**Comment by andrew** [comment]
Yeah that regex isn't great, I'll add that example to the specs and then go about making it more restrictive.

**Comment by jdossett** [comment]
That was quick!   Thanks! :-D
