### ISSUE TITLE
Python "requirements-dev.txt" classified as runtime dependency

### ISSUE THREAD

**Issue by Zac-HD** [librariesio/bibliothecary#414]
...when obviously things in this file are in fact development dependencies.  

[AWS Chalice](https://libraries.io/github/aws/chalice) is a good example, which also demonstrates another Python idiom - people often use multiple suffixes to distinguish requirements files for various purposes.  -docs, -dev, -tools, etc should all be counted as development dependencies (and likewise for the requirements/*.txt forms of these files.

I found this issue when investigating [Hypothesis](https://libraries.io/pypi/hypothesis), a testing library I maintain - libraries.io shows 472 runtime and 14 development dependent repositories, and I'd expect the opposite ratio.

**Comment by andrew** [comment]
Agreed, that's not correct, will pull up some data on the different file names Libraries.io has seen across GitHub to see if there would be any false positives of just seeing anything after the `requirements` and before `.txt` as being dev dependencies

**Comment by brainwane** [comment]
`bleach` [has an example](https://github.com/mozilla/bleach/blob/master/requirements-dev.txt) in case that's useful for investigating.
